name: Build
description: Build application with Maven and create a new Docker image
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: "Name for the Docker image"
    required: true
    default: "default_image_name"
  tag_name:
    description: "Tag for the Docker image"
    required: false

runs:
  using: composite
  steps:
    - name: Set Docker Tag
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi

    - name: Validate Image Name
      shell: bash
      run: |
        if [ -z "${{ inputs.image_name }}" ]; then
          echo "Error: image_name input cannot be empty."
          exit 1
        fi

    - name: Build Docker Image
      shell: bash
      run: |
        NAME="${{ inputs.image_name }}:$TAG"
        if ! docker build . --file "${{ inputs.path_dockerfile }}" --tag "$NAME"; then
          echo "Docker build failed!"
          exit 1
        fi
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
        docker images
