name: CI

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker Tag
        id: set-tag
        shell: bash
        run: |
          if [ -z "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Validate Image Name
        shell: bash
        run: |
          if [ -z "${{ github.event.inputs.image_name }}" ]; then
            echo "Error: image_name input cannot be empty."
            exit 1
          fi

      - name: Build Docker Image
        shell: bash
        run: |
          NAME="${{ github.event.inputs.image_name }}:$TAG"
          if ! docker build "$(dirname "${{ github.event.inputs.path_dockerfile }}")" --file "${{ github.event.inputs.path_dockerfile }}" --tag "$NAME"; then
            echo "Docker build failed!"
            exit 1
          fi
          echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
          echo "Built Docker image: $NAME"
          docker images

      - name: Push Docker Image
        shell: bash
        run: |
          NAME="${{ github.event.inputs.image_name }}:$TAG"
          if ! docker push "$NAME"; then
            echo "Docker push failed!"
            exit 1
          fi
          echo "Successfully pushed Docker image: $NAME"

      - name: Cleanup
        run: docker system prune -f --volumes