name: Push Docker Image
description: Push the Docker image to Docker Hub
inputs:
  docker_username:
    description: 'Docker Hub Username'
    required: true
  image_name:
    description: 'Docker Image Name with Tag'
    required: true

runs:
  using: composite
  steps:
    - name: Tag Docker Image
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.image_name }}"
        DOCKER_USERNAME="${{ inputs.docker_username }}"

        # Tag the image with the Docker Hub username
        if ! docker tag "$IMAGE_NAME" "$DOCKER_USERNAME/$IMAGE_NAME"; then
          echo "Docker tagging failed!"
          exit 1
        fi

        echo "Successfully tagged image as: $DOCKER_USERNAME/$IMAGE_NAME"

    - name: Push Docker Image
      shell: bash
      run: |
        DOCKER_USERNAME="${{ inputs.docker_username }}"
        IMAGE_NAME="${{ inputs.image_name }}"

        # Push the image to Docker Hub
        if ! docker push "$DOCKER_USERNAME/$IMAGE_NAME"; then
          echo "Docker push failed!"
          exit 1
        fi

        echo "Successfully pushed Docker image: $DOCKER_USERNAME/$IMAGE_NAME"
