name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the Docker image to create"
    required: true
    default: "image-name"
runs:
  using: composite
  steps:
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
      cache: maven
  - name: Build with Maven
    shell: bash
    run: mvn -B package -DskipTests --file pom.xml && docker images