name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: BrunooMPS/academy/.github/actions/maven_build@main
      
      - uses: BrunooMPS/academy/.github/actions/docker_build@main
      
      - name: Push Docker Image
        uses: BrunooMPS/academy/.github/actions/docker_build/push.yml  # Update with your action path
        with:
          docker_username: ${{ vars.DOCKERHUB_USERNAME }}
          docker_image_name: "your_image_name"  # Replace with the name generated in the Docker build step
