name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}  # Set Docker Hub username as an environment variable
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}      # Set Docker Hub token as an environment variable
    steps:
      - uses: actions/checkout@v4
      - uses: BrunooMPS/academy/.github/actions/maven_build@main

      - name: Push Docker Image
        uses: BrunooMPS/academy/.github/actions/docker_build@main
        with:
          docker_username: ${{ env.DOCKERHUB_USERNAME }}  # Use environment variable
          docker_image_name: image-name
