name: CI

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Build Docker Image
        uses: ./docker_build  # Assuming your build action is in the docker_build directory
        with:
          path_dockerfile: "./src/main/docker/Dockerfile.jvm"
          image_name: "default_image_name"
          tag_name: "latest" # Or any other tag you prefer

      - name: Push Docker Image
        uses: ./push_image  # Use the newly created push_image action
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}  # Use the username from secrets
          image_name: ${{ env.DOCKER_IMAGE_NAME }}  # Make sure this is set in the build step
