name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker Image
        run: |
          echo "Building Docker image: image-name"
          docker build -t image-name .  # Ensure this matches what you will use later

      - name: Push Docker Image
        uses: BrunooMPS/academy/.github/actions/push_docker_image@main
        with:
          docker_username: ${{ vars.DOCKERHUB_USERNAME }}
          docker_image_name: image-name